CREATE DATABASE rede_social;
USE rede_social;

CREATE TABLE USUARIO(
ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
NOME_USUARIO VARCHAR(50) UNIQUE,
EMAIL VARCHAR(80) UNIQUE,
FOTO_PERFIL LONGBLOB NULL,
DATA_NASC DATE
);

CREATE TABLE NOTIFICACAO(
ID_NOTIFICACAO INT PRIMARY KEY AUTO_INCREMENT,
ORIGEM VARCHAR(255),
DATA_N DATETIME,

FK_ID_USUARIO INT,
FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE POSTAGEM(
ID_POSTAGEM INT PRIMARY KEY AUTO_INCREMENT,
AMEI INT,
NAO_AMEI INT,
CONTEUDO VARCHAR(255),
DATA_PUBLIC DATETIME,

FK_ID_USUARIO INT,
FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE COMENTARIO(
ID_COMENTARIO INT PRIMARY KEY AUTO_INCREMENT,
AMEI INT,
NAO_AMEI INT,
CONTEUDO VARCHAR(255),
DATA_COMEN DATETIME,

FK_ID_POSTAGEM INT,
FOREIGN KEY (FK_ID_POSTAGEM) REFERENCES POSTAGEM(ID_POSTAGEM) ON DELETE CASCADE
);

CREATE TABLE CONTATO(
ID_CONTATO INT PRIMARY KEY AUTO_INCREMENT,
NOME_CONTATO VARCHAR(50),
FOTO_CONTATO BLOB NULL
);

CREATE TABLE CONVERSA(
ID_CONVERSA INT PRIMARY KEY AUTO_INCREMENT,
MENSAGEM VARCHAR(255),
DATA_MENSAGEM DATETIME,
STATUS_MESNAGEM VARCHAR(20),

FK_ID_USUARIO INT,
FK_ID_CONTATO INT,
FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
FOREIGN KEY (FK_ID_CONTATO) REFERENCES CONTATO(ID_CONTATO) ON DELETE CASCADE
);

CREATE TABLE GRUPO(
ID_GRUPO INT PRIMARY KEY AUTO_INCREMENT,
NOME_GRUPO VARCHAR(50) UNIQUE,
DESC_G VARCHAR(255),
DATA_GRUPO DATE
);

CREATE TABLE USUARIO_GRUPO(
ID_USUARIO INT,
ID_GRUPO INT,
CONSTRAINT PK_USUARIO_GRUPO primary key (ID_USUARIO, ID_GRUPO),
CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
CONSTRAINT FK_ID_GRUPO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID_GRUPO) ON DELETE CASCADE
);

CREATE TABLE MEMBRO(
ID_MEMBRO INT PRIMARY KEY AUTO_INCREMENT,
NOME_MEMBRO VARCHAR(25) UNIQUE,
DATA_ENTRADA DATE,
TIPO_MEMBRO VARCHAR(20),
FK_ID_GRUPO INT,
FOREIGN KEY (FK_ID_GRUPO) REFERENCES GRUPO(ID_GRUPO) ON DELETE CASCADE
);


CREATE TABLE TAG(
ID_TAG INT PRIMARY KEY AUTO_INCREMENT,
NOME_TAG VARCHAR(20) UNIQUE
);

CREATE TABLE USUARIO_TAG(
ID_USUARIO INT,
ID_TAG INT,
CONSTRAINT PK_USUARIO_TAG primary key (ID_USUARIO, ID_TAG),
CONSTRAINT FK_ID_USUARIO_TAG_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
CONSTRAINT FK_ID_TAG FOREIGN KEY (ID_TAG) REFERENCES TAG(ID_TAG) ON DELETE CASCADE
);